### PR TITLE
fix: Commit message validation

### PR DESCRIPTION
**Pull request by cameronwaterman**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nisystemlink-clients-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds validation that commit messages adhere to the [Angular style](https://gist.github.com/brianclements/841ea7bffdb01346392c).

This commit would generally have a "build" or "ci" prefix type, but we need to force a version and rebuild as https://github.com/ni/nisystemlink-clients-python/commit/7881a90c7fcfc5dd88228d171f8000b10330b04f did not result in a new version being built.

### Why should this Pull Request be merged?

Ensure we have properly formatted commit messages.

### What testing has been done?

See PR build.

### CODE REVIEW

**Comment by cameronwaterman** [comment]
It looks like if you want the commit message validation step to run against an updated PR title you have to push another commit. Not sure if this is something we want to require for this repo.

**Review by mure — APPROVED** [review]

**Comment by mure** [comment]
> It looks like if you want the commit message validation step to run against an updated PR title you have to push another commit. Not sure if this is something we want to require for this repo.

If this is the case, I think it's too cumbersome to enable

**Comment by spanglerco** [comment]
> It looks like if you want the commit message validation step to run against an updated PR title you have to push another commit. Not sure if this is something we want to require for this repo.

How about https://github.com/aslafy-z/conventional-pr-title-action/issues/165#issuecomment-1066634563?

**Comment by cameronwaterman** [comment]
> > It looks like if you want the commit message validation step to run against an updated PR title you have to push another commit. Not sure if this is something we want to require for this repo.
> 
> How about [aslafy-z/conventional-pr-title-action#165 (comment)](https://github.com/aslafy-z/conventional-pr-title-action/issues/165#issuecomment-1066634563)?

Interesting. Applying that change did rerun the workflow on the new commit, but after changing the PR title the PR check is gone completely.

**Pull request closed without merging**
